"""empty message

Revision ID: a9740ee5bad4
Revises: 26f72a9a3a7e
Create Date: 2025-10-17 17:28:02.773611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9740ee5bad4'
down_revision = '26f72a9a3a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.drop_column('model')
        batch_op.drop_column('manufacturer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('model', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
